---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: 123abc
    source:
      repository: kdziurdz/chat-rooms-web
      access_token: 7032af1db7b60784d18786c2666ada99cd34e4f1

jobs:
  - name: test
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - task: unit-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine/git, tag: "latest"}
          inputs:
            - name: pull-request
          run:
            path: echo
            args: [tests_passed]
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success