---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: 123abc
    source:
      repository: kdziurdz/chat-rooms-web
      access_token: c1f01d1d0f1a149ea63d9bce5285f415315e51c3

jobs:
  - name: test
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: pull-request
        params:
          path: pull-request
          status: pending
      - task: unit-test
        file: pull-request/ci/tasks/test/test.yml
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
      - put: pull-request
        params:
          path: pull-request
          status: success