---
resources:
  - name: app
    type: git
    source:
      uri: https://github.com/kdziurdz/chat-rooms-web
      branch: master

  - name: deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: konrad.dziurdz@gmail.com
      password: ((cf_password))
      organization: sample-service
      space: development
      skip_cert_check: true

jobs:
  - name: deploy-app
    public: true
    serial: true
    plan:
      - get: app
        trigger: true
      - task: build
        file: app/ci-cd/tasks/build/build.yml
      - put: deploy-web-app
        params:
          manifest: build/manifest.yml